version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: matrix-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GO_API_URL=${NEXT_PUBLIC_GO_API_URL}
      - NEXT_PUBLIC_NODE_API_URL=${NEXT_PUBLIC_NODE_API_URL}
    restart: always

networks:
  default:
    name: matrix-network
    external: true
